### ISSUE TITLE
1.2 seems to break projects.

### ISSUE THREAD

**Issue by snaggen** [tats-u/rust-oem-cp#11]
In 1.1 DECODING_TABLE_CP_MAP was defined as
```rust
pub static ref DECODING_TABLE_CP_MAP: OEMCPHashMap<u16, TableType>
```

In 1.2 that changed to 
```rust 
pub static DECODING_TABLE_CP_MAP: OEMCPHashMap<u16, TableType>
```
it is no longer a reference and hence cannot be dereferenced. 

It would be good if this could be clearly stated, and the examples updated. This also seems to break projects like 
https://github.com/BartMassey/codepage-strings since according to semantic versioning 1.1 and 1.2 should be api compatible and hence cargo will happily use 1.2 even though 1.1 is stated in Cargo.toml.

I suggest you pull the 1.2 release and re-release that as 2.0 instead with updated examples.

**Comment by tats-u** [comment]
Sorry I should have called it 2.0.0 instead of 1.2.0. I underestimated the change of hash functions.
I have just released 1.3.0.

**Comment by tats-u** [comment]
@snaggen I have just yanked 1.2.0. Could you try 1.3.0 and tell me whether it works or not?

**Comment by snaggen** [comment]
codepage-strings compiles with 1.3.0

**Comment by tats-u** [comment]
Great for you.
