### ISSUE TITLE
TableType should be Debug and Clone

### ISSUE THREAD

**Issue by BartMassey** [tats-u/rust-oem-cp#5]
It would be great if `TableType` would be `Debug` and `Clone`. I am adding a pull request for this.

**Comment by tats-u** [comment]
Could you tell me why you want to make `TableType` clonable without `.clone()`?

**Comment by BartMassey** [comment]
I'm afraid I don't understand the question?

I currently don't need `Clone` for my [`codepage-strings`](/BartMassey/codepage-strings) crate, but it is [normal](https://rust-lang.github.io/api-guidelines/interoperability.html#c-common-traits) to make published types clonable unless there is a good reason not to. The ability to clone allows things like moving a clone into a thread for applications that want to do that.

I'm not wedded to `Clone`, so if you feel you just want to make `TableType` be `Debug` that's OK, but I don't see any reason why not.

**Comment by tats-u** [comment]
I have confused `Clone` with `Copy`.
Let me merge your PR.

**Comment by tats-u** [comment]
Close as v1.1.0, which contains #6, has just released.

**Comment by BartMassey** [comment]
Thank you!
